fix: update stac api title and description
NASA-IMPACT/veda-backend pull request #379
Opened 2024-05-22 20:37 UTC by smohiudd

Related to https://github.com/NASA-IMPACT/veda-data/issues/124

This PR updated the STAC API title and description.

2024-05-23 15:22 UTC, anayeaye approved these changes

2024-05-23 21:03 UTC, slesaad requested changes
@smohiudd can we make this configurable in the same PR?

2024-05-23 21:05 UTC, smohiudd commented
@slesaad, yes working on some chnages to make this configurable

2024-05-31 14:20 UTC, slesaad approved these changes
lgtm

2024-05-31 15:58 UTC, merged